17.11dz
fd1-53-17/Sinclay pull request #14
Opened 2017-11-18 11:08 UTC by Sinclay

please review

2017-11-19 20:43 UTC, antonkulakov-it requested changes

2017-11-19 20:43 UTC, antonkulakov-it commented on 17.11dz/1/assets/z-cards.html
> +    <div class="card1"><img src="img/card1.png"></div>
задание выполнено не верно. Нужно использовать спрайты.

2017-11-19 20:43 UTC, antonkulakov-it commented on 17.11dz/2/assets/absolute_chessboard.html
> +            <div class="white"><img src="img/pawn_black.png"></div>
задание выполнено не верно. 
нужно использовать css и спрайты для расстановки фигур.

2017-11-19 20:43 UTC, antonkulakov-it commented on 17.11dz/2/assets/absolute_chessboard.html
> +            <div class="white"><img src="img/pawn_black.png"></div>
Вырезать фигуры из файла не нужно

2017-11-20 06:26 UTC, Sinclay commented
please review

2017-11-22 04:04 UTC, antonkulakov-it approved these changes

2017-11-22 04:04 UTC, merged