27.11dz
fd1-53-17/Sinclay pull request #21
Opened 2017-11-28 10:44 UTC by Sinclay

please review

2017-11-29 05:33 UTC, antonkulakov-it requested changes

2017-11-29 05:33 UTC, antonkulakov-it commented on 27.11dz/1/assets/css/mediafootball.css
> +        bottom: -220px;
может заходить на контент.

2017-11-29 11:42 UTC, Sinclay commented
corrected, please review

2017-12-12 18:39 UTC, antonkulakov-it approved these changes

2017-12-12 18:39 UTC, merged