01.11a
fd1-53-17/Sinclay pull request #3
Opened 2017-11-01 17:45 UTC by Sinclay

please review

2017-11-03 04:19 UTC, antonkulakov-it requested changes
заменить кавычки и минусы мнемониками

2017-11-03 04:19 UTC, antonkulakov-it commented on homework01/VIZBOR/vechno_student.html
> +    <p align="justify" id="first paragraph">Когда пишут или говорят о студенческих песнях, многие впадают в ошибку - путают студенческие песни с туристскими. Давайте на этот раз не совершим ее. Студе
"ошибку минус путают"
а должно быть "ошибку тире путают". Заменить на мнемонику.

2017-11-03 04:19 UTC, antonkulakov-it commented on homework01/VIZBOR/vechno_student.html
> +    <p align="justify">В свое время драматург Михаил Львовский написал песню, которую студенчество по праву считает "своей", хотя написана она была не студентом и не о студентах. Это песня "Глобус".
кавычки должны быть заменены мнемоникой

2017-11-03 11:52 UTC, Sinclay commented
please review vechno_student corrected

2017-11-08 04:01 UTC, antonkulakov-it approved these changes

2017-11-08 04:01 UTC, merged